spring:
  config:
    name: project2
  datasource:
    url: jdbc:postgresql://localhost:5432/journal
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl_auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
  mvc:
    throw-exception-if-no-handler-found: true
